### ISSUE TITLE
The meaning of predicted depth

### ISSUE THREAD

**Issue by stunback** [baegwangbin/MaGNet#1]
Hello, I'm curious about the meaning of model prediction. Does it represent a relative depth or absolute depth in meters?

**Comment by baegwangbin** [comment]
Hi, 

The depth maps are in meters (i.e. absolute depth). 

The output of MaGNet has a shape of (B, H, W, 2), where B is the batch size and H (and W) is the input height (and width). The first output channel is the mean depth, and the second channel is the standard deviation. They correspond to the mu and sigma of a Gaussian distribution.
