### ISSUE TITLE
How to visualize sigma (uncertainty) with the same color map as that used in your paper?

### ISSUE THREAD

**Issue by EchoTHChen** [baegwangbin/MaGNet#10]
I cannot find the colormap similar to your paper in opencv-python. Could you share your visualization code about the sigma? Thanks!

**Comment by baegwangbin** [comment]
Hi, we used the 'Reds' colormap from matplotlib. You can do something like:

`plt.imsave(target_image_path, predicted_sigma, cmap='Reds')`

Note that `predicted_sigma` should be a NumPy float array with shape H X W.

**Comment by EchoTHChen** [comment]
Thanks
